### ISSUE TITLE
Install Problem:  IntelliJ plugin refuses to use mmt.jar v15

### ISSUE THREAD

**Issue by stub22** [UniFormal/IntelliJ-MMT#1]
Installed IntelliJ plugin (Dec. 25 merry version) from  marketplace.
I use menu "New Project -> MMT Mathhub", and then I am prompted to select mmt.jar.
I give it latest mmt.jar, version 15.0.0  (from systems/MMT/deploy/mmt.jar).
But intelliJ plugin still says "Please select a valid mmt.jar (requires 15.0.0 or higher)", 
and does not continue.  See screenshots.

IDE environment:
MS Windows 10, IntelliJ 2018.3.3 Community with internal OpenJDK 1.8.
See screenshot "ij_idea_version.png" for exact versions used by IDE
(My own builds use Sun JDK 1.8 - probably irrelevant)

On same Windows box I am able to run MMT v15 at console (using my Sun JDK 1.8):
>mmt>show mmt
> user: 'show mmt'
> user: MMT Version     : 15.0.0 (built 2018/12/18 20:59:50)
> user: Run Style       : FatJar(C:\_root\_japp\mmt_v15\systems\MMT\deploy\mmt.jar)
> user: Build time      : 2018/12/18 20:59:50

![ij_idea_version](https://user-images.githubusercontent.com/1082227/51090107-2059b900-1734-11e9-8fbe-03c68113a792.png)
![jb_plugin_installing](https://user-images.githubusercontent.com/1082227/51090108-20f24f80-1734-11e9-816a-e8c04a25e34c.png)
![selecting_mmt](https://user-images.githubusercontent.com/1082227/51090110-20f24f80-1734-11e9-9e70-4a59e8183c75.png)
![mmt_jar_fails](https://user-images.githubusercontent.com/1082227/51090109-20f24f80-1734-11e9-9326-5265979eeeb1.png)

**Comment by Jazzpirate** [comment]
Thanks for letting me know! The bug has been fixed with the latest commit c1c949946d664da0cadd494fed4abfa2a8c7451e. An update has been submitted to the IntelliJ plugin repositry, pending approval (see [here](https://plugins.jetbrains.com/plugin/11450-mmt/update/54042)). You can either update your plugin manually or wait for the new version to be approved for the IntelliJ market place :)
