### ISSUE TITLE
MMT plugin v16 not compatible with IntelliJ Ultimate 2019.2

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/IntelliJ-MMT#15]
2019.2 is the new version, and the MMT plugin is incompatible. Unfortunately, I updated.

**Comment by Jazzpirate** [comment]
Will be fixed with the next MMT release version

**Comment by ComFreek** [comment]
It seems that [MMT v18.0.0 came out 18 days ago](https://github.com/UniFormal/MMT/releases/tag/v18.0.0) and your commit https://github.com/UniFormal/IntelliJ-MMT/commit/cac36b491b5080b3a3a5a95c747c1509888429dc should already have accounted for IntelliJ 2019.2. I still can't find MMT in the marketplace from within IntelliJ 2019.2 Did you push it to the marketplace? :smile:

**Comment by Jazzpirate** [comment]
I did ;)

Note that if you had the plugin previously installed and it was *deactivated* because of version compatibilities, it might be that it doesn't show in the marketplace because it's already installed. In that case you have to find it in your list of *installed* plugins, update it and activate it ;)

**Comment by ComFreek** [comment]
Reinstalled IntelliJ again, that did it. Thanks!
