### ISSUE TITLE
Disable indexing on project's mmt.jar

### ISSUE THREAD

**Issue by ComFreek** [UniFormal/IntelliJ-MMT#19]
Every time you create a new MMT project or exchange the mmt.jar referenced by an existing project, it gets reindexed. Depending on your computer, this unfortunately may take minutes.

**Is it possible to somehow deactiate this behavior from withint the plugin?**

Also while it indexes, you **can't do anything**. You can neither install new archives nor type something in the MMT shell.

**Comment by Jazzpirate** [comment]
Unfortunately no.

Indexing in IntelliJ is scala specific, and the mmt.jar is a dependency of a MathHub project - necessarily, since you want to be able to edit and compile scala files in MMT archives.

Having said that, usually that is supposed to happen only once every time a new mmt version is released, and when creating a new project which also only needs to happen once ever.
